
import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author halpin
 */
public class PongPanel extends javax.swing.JPanel {
    private Graphics g;
    private Graphics2D g2D;
    PongModel model;

    /**
     * Creates new form PongPanel
     */
    public PongPanel(Pong controller, PongModel m) {
        model = m;
        initComponents();
    }
    
    @Override
    public Dimension getMinimumSize() {
        return getPreferredSize();
    }
    
    @Override
    public Dimension getPreferredSize() {
        return model.d;
    }
    
    @Override
    public Dimension getMaximumSize() {
        return getPreferredSize();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        System.out.println("paint component");
        super.paintComponent(g);        
        drawBall(g, model.ball);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
        
//    private void drawDashedLine(Color c, int x1, int y1, int x2, int y2) {
//        // TODO: figure out who should store this
//        float dash1[] = {10.0f};
//        g2D.setStroke(new BasicStroke(1.0f,
//                        BasicStroke.CAP_BUTT,
//                        BasicStroke.JOIN_MITER,
//                        10.0f, dash1, 0.0f));
//        g2D.setColor(c);
//        g2D.drawLine(x1, y1, x2, y2);
//    }
//    
//    
//    private void drawPlayer(Player player) {
//        g.setColor(Color.WHITE);
//        Point p = player.getBottomLeft();
//        System.out.println(p.x);
//        g.fillRect((int)p.x, (int) p.y, player.d.width, player.d.height);
//        g.drawRect((int)p.x, (int) p.y, player.d.width, player.d.height);
//    }
    
    private void drawBall(Graphics g, Ball b) {
        System.out.println("Draw ball");
        g.setColor(Color.BLUE);
        Point bL = b.getBottomLeft();
        g.drawOval((int)bL.x, (int)bL.y, b.radius, b.radius);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
